apiVersion: v1
kind: Service
metadata:
  name: store-db
  namespace: prod
  labels:
    app: store-db
spec:
  type: ClusterIP
  ports:
    - name: store-db
      port: 3306
  selector:
    app: store-db

