apiVersion: v1
kind: Service
metadata:
  name: notification-db
  namespace: prod
  labels:
    app: notification-db
spec:
  type: ClusterIP
  ports:
    - name: notification-db
      port: 3306
  selector:
    app: notification-db

