apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8800
      port: 8800
  selector:
    app: product-service
