apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-simple-app
  labels:
    app: kubernetes-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-simple-app
  template:
    metadata:
      name: kubernetes-simple-app
      labels:
        app: kubernetes-simple-app
    spec:
      containers:
        - name: kubernetes-simple-app
          image: nginx
          imagePullPolicy: IfNotPresent
          # 준비된 볼륨을 실제 컨테이너에 연결
          volumeMounts:
            - mountPath: "/tmp"
              name: myvolume
      # 사용할 볼륨 설정
      # 사용할 pvc 설정
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: pvc-hostpath
      restartPolicy: Always
