apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: nginx-statefulset-service
  labels:
    app: nginx-statefulset-service
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx-statefulset-service