apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: prod
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        nodegroup: util
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config
              mountPath: /etc/redis
          command:
            - "redis-server"
            - "--appendonly"
            - "yes"
            - "--requirepass"
            - "123456"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          # 애플리케이션이 시작된 뒤 초기화 작업이 마무리되어 준비되었는지 검사
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 20
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: pvc-redis
        - name: config
          configMap:
            name: redis-config
