apiVersion: v1
kind: Service
metadata:
  name: giftcard-db
  namespace: prod
  labels:
    app: giftcard-db
spec:
  type: ClusterIP
  ports:
    - name: giftcard-db
      port: 3306
  selector:
    app: giftcard-db

