apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8000
      port: 8000
  selector:
    app: apigateway-service
