apiVersion: v1
kind: Service
metadata:
  name: giftcard-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 9100
      port: 9100
  selector:
    app: giftcard-service
