apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: prod
  labels:
    app: product-db
spec:
  type: ClusterIP
  ports:
    - name: product-db
      port: 3306
  selector:
    app: product-db
