apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8900
      port: 8900
  selector:
    app: order-service
