apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: prod
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: mongodb
