apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8300
      port: 8300
  selector:
    app: delivery-service
