apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: prod
  labels:
    app: user-db
spec:
  type: ClusterIP
  ports:
    - name: user-db
      port: 3306
  selector:
    app: user-db

