apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  my.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    datadir=/var/lib/mysql
    authentication-policy = mysql_native_password

    [client]
    default-character-set = utf8mb4
    
