apiVersion: v1
kind: Service
metadata:
  name: wishlist-db
  namespace: prod
  labels:
    app: wishlist-db
spec:
  type: ClusterIP
  ports:
    - name: wishlist-db
      port: 3306
  selector:
    app: wishlist-db

