apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service
  namespace: prod
  labels:
    app: store-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      name: store-service
      labels:
        app: store-service
    spec:
      containers:
        - name: store-service
          image: nowgnas/bb:store
          imagePullPolicy: Always
          ports:
            - containerPort: 8700
          env:
            - name: USE_PROFILE
              value: "prod"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8700
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8700
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
      restartPolicy: Always

