apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: prod
  labels:
    app: payment-db
spec:
  type: ClusterIP
  ports:
    - name: payment-db
      port: 3306
  selector:
    app: payment-db

