apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: prod
  labels:
    app: order-db
spec:
  type: ClusterIP
  ports:
    - name: order-db
      port: 3306
  selector:
    app: order-db

